apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hello-gcp-gateway
  namespace: demo
  annotations:
    # Reference the traffic policy
    ngrok.com/traffic-policy: hello-policy
spec:
  gatewayClassName: ngrok
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-gcp-route
  namespace: demo
spec:
  parentRefs:
  - name: hello-gcp-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: hello-gcp
      port: 80
---
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: NgrokTrafficPolicy
metadata:
  name: hello-policy
  namespace: demo
spec:
  policy:
    on_http_response:
      - actions:
          - type: add-headers
            config:
              headers:
                x-demo-source: "ngrok-gateway-api"
                x-powered-by: "ngrok"
