apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gcp-gateway
  namespace: demo
spec:
  gatewayClassName: ngrok
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-gcp-route
  namespace: demo
spec:
  parentRefs:
  - name: gcp-gateway
  hostnames:
  - "*.ngrok.app"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: hello-gcp
      port: 80
