apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: AgentEndpoint
metadata:
  name: hello-aws-binding
  namespace: demo
spec:
  url: http://aws-service.demo
  bindings:
    - kubernetes
  upstream:
    url: http://hello-aws.demo:80
