apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: AgentEndpoint
metadata:
  name: hello-aws-binding
  namespace: demo
  annotations:
    # Reference the traffic policy
    ngrok.com/traffic-policy: hello-policy
spec:
  url: http://aws-service.demo
  bindings:
    - kubernetes
  upstream:
    url: http://hello-aws.demo:80
---
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: NgrokTrafficPolicy
metadata:
  name: hello-policy
  namespace: demo
spec:
  policy:
    on_http_response:
      - actions:
          - type: add-headers
            config:
              headers:
                x-demo-source: "ngrok-bindings"
                x-cluster: "aws-cluster"
